// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWMyWK4Fll-lRzP3HfBFm-QXVKIHaeGIk',
    appId: '1:401818706843:web:ec2eb9dcda794932df773e',
    messagingSenderId: '401818706843',
    projectId: 'crud-2323e',
    authDomain: 'crud-2323e.firebaseapp.com',
    storageBucket: 'crud-2323e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqHWBLEcfGS7AyY6sLq768VLD7gj0KY6c',
    appId: '1:401818706843:android:fe928985d80f8563df773e',
    messagingSenderId: '401818706843',
    projectId: 'crud-2323e',
    storageBucket: 'crud-2323e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBRVBfX6avlN36YL5jtIE8lUfJm9bYsdA',
    appId: '1:401818706843:ios:2c65988bc238552edf773e',
    messagingSenderId: '401818706843',
    projectId: 'crud-2323e',
    storageBucket: 'crud-2323e.appspot.com',
    iosBundleId: 'com.example.flutterCrut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBRVBfX6avlN36YL5jtIE8lUfJm9bYsdA',
    appId: '1:401818706843:ios:2c65988bc238552edf773e',
    messagingSenderId: '401818706843',
    projectId: 'crud-2323e',
    storageBucket: 'crud-2323e.appspot.com',
    iosBundleId: 'com.example.flutterCrut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWMyWK4Fll-lRzP3HfBFm-QXVKIHaeGIk',
    appId: '1:401818706843:web:2dc1c8b0785471f8df773e',
    messagingSenderId: '401818706843',
    projectId: 'crud-2323e',
    authDomain: 'crud-2323e.firebaseapp.com',
    storageBucket: 'crud-2323e.appspot.com',
  );
}
